spring.application.name: catalogo
server.port: 8083

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  cloud:
    stream:
      default-binder: rabbit
      default-content-type: application/json
      bindings:
        product-out-0:
          destination: product
          content-type: application/json

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  logging:
    level:
      org.springframework.cloud.stream: DEBUG
      org.springframework.context: DEBUG

---
server.port: 8080
spring:
  config.activate.on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/postgres
  rabbitmq:
    host: message
