spring.application.name: catalogo
server.port: 8084

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest